### ISSUE TITLE
Replace method calls

### ISSUE THREAD

**Issue by greg0ire** [yannickl88/features-bundle#5]
Service definitions that use factories can't afford to use the `arguments` key to do injection. A good solution might be to replace method call arguments. This will have the side effect to make the `Feature` as an optional dependency possible.

**Comment by yannickl88** [comment]
After some discussion I think if you cannot use the arguments you can always use the [`FeatureContainer`](https://github.com/yannickl88/features-bundle/blob/master/src/Feature/FeatureContainerInterface.php) (service name is `features.container`). This holds all the registered features and has a `::get()` method for fetching them. You can always use that in combination with the method call arguments.

I'm closing this for now. If there are better suggestions or options a new issue, or (prefereably) a PR, can be created.

**Comment by greg0ire** [comment]
Also, decoration can be used to be able to use the `arguments` key.
